# Generated by Django 2.2.7 on 2019-11-10 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='pdf',
            new_name='Documento',
        ),
        migrations.RenameField(
            model_name='ficha',
            old_name='type',
            new_name='Tema',
        ),
        migrations.RenameField(
            model_name='ficha',
            old_name='title',
            new_name='Titulo',
        ),
    ]
