# Generated by Django 2.2.7 on 2019-11-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20191110_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='Tema',
            field=models.CharField(default='', max_length=40, null=True),
        ),
    ]
