# Generated by Django 2.2.7 on 2019-11-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20191110_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='Tema',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
