# Generated by Django 2.2.7 on 2019-11-12 23:48

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20191110_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', embed_video.fields.EmbedVideoField(verbose_name='Video')),
                ('Titulo', models.CharField(max_length=40)),
                ('Tema', models.CharField(max_length=40)),
            ],
        ),
    ]
