# Generated by Django 3.0 on 2019-12-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Status',
            field=models.CharField(choices=[('p', 'Published'), ('h', 'Hidden')], default='h', max_length=1),
        ),
    ]
