# Generated by Django 2.2.7 on 2020-01-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Periodo',
            field=models.CharField(default=1, max_length=2),
        ),
    ]
