# Generated by Django 2.2.7 on 2020-01-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_video_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='Status',
            field=models.CharField(choices=[('p', 'Published'), ('h', 'Hidden')], default='h', max_length=1),
        ),
        migrations.AddField(
            model_name='video',
            name='Status',
            field=models.CharField(choices=[('p', 'Published'), ('h', 'Hidden')], default='h', max_length=1),
        ),
    ]
