# Generated by Django 2.2.7 on 2020-01-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20200107_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='Tipo',
            field=models.CharField(default='Ficha', max_length=40),
        ),
        migrations.AddField(
            model_name='video',
            name='Tipo',
            field=models.CharField(default='Video', max_length=40),
        ),
    ]
