# Generated by Django 3.0 on 2019-12-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_ficha_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='Tipo',
            field=models.CharField(default='Ficha', max_length=40),
        ),
        migrations.AddField(
            model_name='video',
            name='Tipo',
            field=models.CharField(default='Video', max_length=40),
        ),
    ]
